### ISSUE TITLE
"TypeError: 'float' object is not callable"

### ISSUE THREAD

**Issue by lilyfalk** [monroews/CEE4530#36]
I get the error mentioned in the subject line when i run the code below but do not understand how to alter the code to get it to run...

```python
pec1 = 1
pec10 = 10
pec100 = 100
Q = 0.38*(u.L/u.min)
Vr = 2.25*(u.L)
theta = Vr/Q
t = np.linspace(0.1, 3, num=1)*u.min
tx = t/theta
Etx1 = math.sqrt(pec1/(4*math.pi*tx))*math.e((-((1-tx)**2)*pec1)/(4*tx))
```

**Comment by emarroquin** [comment]
Can you run it line by line to see where the error pops up? I noticed that sometimes the pint package does some weird things to arrays.

**Comment by Megan-McE** [comment]
The error might be that you have "math.e" when I think it should be "math.exp"?

**Comment by lilyfalk** [comment]
The error pops up on the last line and i have tried both math.e and math.exp and neither work

**Comment by monroews** [comment]
math doesn't yet support pint units. You can use numpy whenever possible because it is compatible with units. In this case np.exp is your friend. If you need to use a function that is not available in numpy you will need to strip the units using  .magnitude (example theta.magnitude) to remove the units. If you use that option make sure that you know what the units are that are being stripped off. 

You can convert the units in place by using the .ito command. For example
`V_filter = 1.85*u.mm/u.s

A_filter = 0.5*u.mm * 10*u.mm
Q_filter = V_filter*A_filter
Q_filter.units  will display in cubic millimeters per second
Q_filter.ito(u.ul/u.min)
Q_filter.units` will display in uL/min
