### ISSUE TITLE
How to import a tab delimited txt file as an array.

### ISSUE THREAD

**Issue by jillianwhiting** [monroews/CEE4530#8]
```python
file = pd.read_csv('filename.txt',delimiter='\t')
array = np.array(file)
```
This works only if everything in the text file is a number, if you have something in the text file that is not a number you need to remove that either before importing it or if it is the top rows you can add a header input which says how many lines at the top should not be imported. The code below would not import the first row of the file.
```python
file = pd.read_csv('filename.txt',delimiter='\t', header =1)
array = np.array(file)
```

**Comment by WPennock** [comment]
I think the flexibility issue here is not with Pandas, but with Numpy. I would advise not converting the entire data frame into a Numpy array. Instead, I would advocate converting columns of the data frame columns as you need them. There may be a more elegant solution, but that is what I have done. So, for example, let's say you have a column of influent turbidity values you want to convert into a column, and the header in the .csv reads "Influent Turbidity (NTU)". In that case, what I would do is:

`from aide_design.units import unit_registry as u # in order to add units

file = pd.read_csv('datalog 2-13-2018.xls',delimiter='\t') # My datalog files are saved as .xls
Inf = file["Influent Turbidity (NTU)"].values*u.NTU # Extract column from "file" data frame, extract values (makes array), and multiply by assigned units.
`

**Comment by monroews** [comment]
The updated method to import AguaClara code is
from aide_design.play import *
This one line is equivalent to 
# Third-party imports
- import numpy as np
- import pandas as pd
- import matplotlib.pyplot as plt
- import matplotlib

# AIDE imports
- import aide_design
- import aide_design.pipedatabase as pipe
- from aide_design.units import unit_registry as u
- from aide_design import physchem as pc
- import aide_design.expert_inputs as exp
- import aide_design.materials_database as mat
- import aide_design.utility as ut
- import aide_design.k_value_of_reductions_utility as k
- import aide_design.pipeline_utility as pipeline
- import warnings

**Comment by WPennock** [comment]
@monroews Thank you, I have updated my code accordingly! It's nice to see how all of this is evolving.
